# Generated by Django 3.1.5 on 2021-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_loader', '0002_auto_20210826_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Others', 'others')], max_length=100),
        ),
    ]
