# Generated by Django 3.1.5 on 2021-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_loader', '0003_auto_20210826_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Prefered_Job_City',
            field=models.CharField(choices=[('chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Gurugram', 'Gurugram'), ('Mumbai', 'Mumbai'), ('Noida', 'Noida'), ('Lucknow', 'Lucknow')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
